/* ============================================================
   agent-demo.js
   A small, honest simulation of an agentic workflow: every step
   below is scripted, not generated by a live model or connected
   to any real tool. It exists to show HOW an agent loop reasons —
   observe, think, call a tool, check the result, and stop for a
   human before taking any real action — using one of the case
   studies from the AI Portfolio page as the running example.

   Playback starts the moment the console scrolls into view (via
   IntersectionObserver — the same pattern main.js uses for its
   other reveal effects), not on a fixed timer from page load.
   That matters here specifically: the console sits inside a
   .reveal wrapper that's invisible until scrolled to, so starting
   the animation on a page-load timer meant it finished playing
   while still hidden — by the time someone scrolled down, every
   step had already appeared and it looked like a static, broken
   block instead of something "thinking". Starting playback on
   intersection keeps the animation and the reveal in sync.
   ============================================================ */

const AGENT_STEPS = [
  { type: 'goal',       badge: 'GOAL',       text: 'Draft this week\u2019s status update for the Kutubi platform.' },
  { type: 'observe',    badge: 'OBSERVE',    text: 'Checking connected project tools for the current state.' },
  { type: 'tool',       badge: 'TOOL CALL',  text: '<code>get_tickets(project: "Kutubi", updated_since: "7d")</code>' },
  { type: 'result',     badge: 'RESULT',     text: '14 tickets updated &middot; 2 blockers flagged &middot; 1 milestone completed.' },
  { type: 'think',      badge: 'THINK',      text: 'Blockers need to be surfaced first; the milestone is the headline for stakeholders.' },
  { type: 'tool',       badge: 'TOOL CALL',  text: '<code>draft_report(sections: ["Highlights", "Blockers", "Next steps"])</code>' },
  { type: 'result',     badge: 'RESULT',     text: 'Draft generated \u2014 3 sections, ~180 words, blockers listed first.' },
  { type: 'checkpoint', badge: 'CHECKPOINT', text: 'Holding for human review \u2014 this is where a guardrail belongs.' },
  { type: 'done',       badge: 'DONE',       text: 'Waiting on PM approval. Nothing is sent to stakeholders automatically.' }
];

const AGENT_STEP_DELAY_MS = 650;

function buildAgentStep(step, index, reduceMotion) {
  const el = document.createElement('div');
  el.className = `agent-step agent-step--${step.type}`;
  if (!reduceMotion) {
    el.style.animationDelay = `${index * AGENT_STEP_DELAY_MS}ms`;
  }
  el.innerHTML = `
    <span class="agent-step__badge">${step.badge}</span>
    <span class="agent-step__text">${step.text}</span>
  `;
  return el;
}

function playAgentDemo() {
  const log = document.querySelector('[data-agent-log]');
  if (!log) return;

  const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  log.innerHTML = '';
  AGENT_STEPS.forEach((step, i) => {
    log.appendChild(buildAgentStep(step, i, reduceMotion));
  });
}

function initAgentDemo() {
  const log = document.querySelector('[data-agent-log]');
  const consoleEl = document.querySelector('.agent-console');
  if (!log || !consoleEl) return;

  const replayBtn = document.querySelector('[data-agent-replay]');
  if (replayBtn) {
    replayBtn.addEventListener('click', playAgentDemo);
  }

  // No IntersectionObserver support (very old browsers): just play immediately
  // rather than leaving the console permanently empty.
  if (!('IntersectionObserver' in window)) {
    consoleEl.classList.add('is-visible');
    playAgentDemo();
    return;
  }

  const observer = new IntersectionObserver((entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        // Drive the reveal fade ourselves (rather than leaving it to
        // main.js's separate, differently-timed observer) so the
        // console fading in and the steps starting to play happen
        // at the same moment.
        consoleEl.classList.add('is-visible');
        playAgentDemo();
        observer.unobserve(entry.target);
      }
    });
  }, { threshold: 0.3 });

  observer.observe(consoleEl);
}

document.addEventListener('DOMContentLoaded', initAgentDemo);
